atina/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^atinapp/', include('atinapp.urls', namespace='atinapp')),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

atinapp/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.contrib.auth import views as auth_views


from .views import(
    homeView,
    loginView,
    loginAuth,
    signinView,
    #registerView,
    user_create,
    fetch_all_users,
    fetch_messages,
    logout_new,






    #user_create,
    loggedin,
    invalid_login,
    #register,
    #user_detail,
    user_list,
    user_update,
    user_delete,

    profile,
    msg_resp,


#for message
    msg_create,

    message_detail,
    message_list,
    message_update,
    message_delete,
    fetch_countries,
    fetch_states,
    message_type,






)

urlpatterns = [





    #new work
    url(r'^homepage/$', homeView, name="home"),
    url(r'^login/$', loginView, name="login"),
    url(r'^auth_new/$', loginAuth, name = 'auth_new'),
    url(r'^auth_new/$', signinView, name="loggedin"),
    url(r'^logout/$', auth_views.logout, {'template_name': 'indexb.html'}, name='logout'),



    url(r'^signup/$', user_create, name = 'signup'),
    #url(r'^regi/$', user_create, name = 'register'),

    #url(r'^signups/$', signup, name="signsup"),












    #url(r'^auth/$', signin, name = 'auth'),
    url(r'^autht/$', msg_create, name='create_message'),
    url(r'^authr/$', msg_resp, name='create_resp'),
    url(r'^invalid/', invalid_login, name='invalid_log'),
    url(r'^dashboard/$', loggedin, name='userpage'),

    #url(r'^profile/(?P<id>\d+)/$', user_detail, name = 'profile'),
    url(r'^profile/(?P<id>\d+)/$', profile, name='profile'),
    url(r'^list_usr/$', user_list, name = 'list_user'),
    url(r'^edit_profile/(?P<id>\d+)/$', user_update, name = 'edit_user'),
    url(r'^(?P<id>\d+)/delete_usr/$', user_delete, name = 'delete_user'),






    #message


    url(r'^msg/$', message_list, name = 'list_message'),
    url(r'^(?P<parent>\d+)/msg/$', message_detail, name = 'detail_message'),
    url(r'^(?P<id>\d+)/edit_message/$', message_update, name='update_message'),
    url(r'^(?P<id>\d+)/delete_message/$', message_delete, name='delete_message'),
    url(r'^fetch_countries/$', fetch_countries),
    url(r'^fetch_states/$', fetch_states),



    url(r'^all_user/$', fetch_all_users, name='all_user'),
    url(r'^all_msg/$', fetch_messages, name='all_user'),
    url(r'^msg_type/$', message_type, name='msg_type'),


]

templates/comment.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
</head>
<body>


<form method="POST" action="">{% csrf_token %}
    {{ form.as_p }}
    {{ form1.as_p }}
    <input type="submit" value="Register">

</form>

</body>
</html>

templates/indexb.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
    <title>Atina</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/font-awesome/css/font-awesome.css' %}" rel="stylesheet">
     <link href="{% static 'css/animate.css' %}" rel="stylesheet">

    <!-- Custom Fonts -->

    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>





    <link href="{% static 'css/creative.min.css' %}" rel="stylesheet">





    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body ng-app="atina">
<nav class="nav nav-tabs" role="navigation">
            		<div class="navbar-header">
                		<button aria-controls="navbar" aria-expanded="false" data-target="#navbar" data-toggle="collapse" class="navbar-toggle collapsed" type="button">
                    		<i class="fa fa-reorder"></i>
                		</button>
                		<a href="{% url 'atinapp:home' %}" class="navbar-brand">Logo<br><br></a>
            		</div>
            		<div class="navbar-collapse collapse" id="navbar">

            			<ul class="nav navbar-top-links navbar-right">
                    		<li><a href="{% url 'atinapp:login' %}"><i class="fa fa-sign-in"></i> Log in</a></li>
                		</ul>

                		<ul class="nav navbar-top-links navbar-right">
                    		<li class="active"><a href="{% url 'atinapp:signup' %}"><i class="fa fa-gears"></i> Sign up </a></li>
                		</ul>

            			<ul class="nav navbar-top-links navbar-right active">
                    		<li><a href="{% url 'atinapp:home' %}"><i class="fa fa-dashboard"></i> Home </a></li>
                		</ul>


            		</div>
        		</nav>

<div class="jumbotron">
  <h1>Atina</h1>
  <p>Get your apps/device solution here</p>
  <p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a></p>
</div>
<div style="margin-top=50px;"class="container" ng-controller="messageController" ng-init="init()">
	<div class="row">
	  <div class="col-sm-4 col-md-4">
		<div class="thumbnail">

		  <div class="caption">
			<h3>Message Category</h3>
			<p>
			  <ul>
				<li ng-repeat="mtype in message_types" ng-click="get_messages(mtype.id)">
					<span ng-bind="mtype.name | uppercase " ></span>
				</li>
			</ul>
			   <ul>
				  <li ng-repeat=" k in users">
					  <span ng-bind ="k.title"></span>
				  </li>
				</ul>
			  </p>

		  </div>
		</div>
	  </div>


	  <div class="col-sm-4 col-md-4">
		<div class="thumbnail">

		  <div class="caption">
			<h3>Issues</h3>
			<p ng-show="mtype.id == id">
				<ul>
						<li ng-repeat="message in messages | filter:0" value="[[ message.id ]]" ng-model="messages" ng-click="get_child(message.id)">
							<span ng-bind="message.msg_content |uppercase"></span>
						</li>
						<span ng-bind="mtype.name | uppercase " ></span>
					</ul>
				</p>

		  </div>
		</div>
	  </div>


	  <div class="col-sm-4 col-md-4">
		<div class="thumbnail">

		  <div class="caption">
			<h3>Responses</h3>
				<p>
				  <ul>
				  <li ng-repeat="child in responses">
					  <span ng-bind="child.msg_content"></span>
				  </li>
				</ul>
			  </p>
			</div>
		</div>
	  </div>
	</div>
</div>
<script type="text/javascript">
    var base_url = "{{request.build_absolute_uri}}";
    var caller = "home";
    var host = base_url.replace(caller,'');
   // alert(host + "groups/");
</script>
    <script src="{% static 'js/jquery-2.1.1.js' %}"></script>
	<script src="{% static 'js/angular.v1.5.2.js' %}"></script>
    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
<script type="text/javascript">
	 var mainApp = angular.module('atina', [], function($interpolateProvider) {
            $interpolateProvider.startSymbol('[[');
            $interpolateProvider.endSymbol(']]');
        });

         mainApp.controller('messageController',['$scope', '$interval', '$http', function($scope, $interval, $http) {
            $scope.message_types = [];
            $scope.messages = [];
            $scope.id = 0;
            $scope.message_types_selected = [];
            $scope.parentdata = [];
            $scope.childdata = [];
            $scope.users = [];

            $scope.get_messages = function(mid){
                //console.log(mid, $scope.message_types);

                for(var c in $scope.message_types){
                    if($scope.message_types[c].id == mid ){
                        $scope.messages = $scope.message_types[c].messages;
                        break;
                    }
                }
                $scope.id = mid;

            }

            $scope.get_child = function(parent_id){
            	//alert(parent_id);
            	console.log($scope.messages);
            //for (var k in $scope.messages){
			//var parent_id = $scope.messages[k].parent;
                function filter_for_parent(element){	if (element.parent ==  parent_id){ return true; } return false; }
                $scope.responses =  $scope.messages.filter(filter_for_parent);
              	//console.log($scope.responses);
			//}

            }
            $scope.init = function() {

                fetchData();

                //fetch data test: parent



            };

            var fetchData = function(){


                var mtype = {};
                $http({
                    method  : 'GET',
                    url : 'http://192.168.25.214:8000/atinapp/all_user/',
                }).success(function(users) {
                        //console.log(users);
                        for (var k in users )
                        {console.log (users[k].title);}

                $http({
                    method  : 'GET',
                    url : 'http://192.168.25.214:8000/atinapp/msg_type/',
                }).success(function(message_types) {
                        //console.log(message_types);
                        $http({
                            method  : 'GET',
                            url : 'http://192.168.25.214:8000/atinapp/all_msg/',
                        }).success(function(messages) {
                               //console.log(messages);
                                for(var c in message_types){
                                    mtype.name = message_types[c].msg_type;
                                    mtype.id = message_types[c].id;
                                    //console.log(mtype.name);
                                    mtype.messages=[];
                                    //console.log(mtype.messages);

                                    for(var s in messages){

                                        if(messages[s].msg_type == message_types[c].id ){
                                            mtype.messages.push(messages[s]);
                                        }

                                    }
                                    $scope.message_types.push(mtype);
                                    mtype = {};
                                }
                        });
                });
                });
            }

            // listen on DOM destroy (removal) event, and cancel the next UI update
            // to prevent updating time after the DOM element was removed.
             $scope.$on('$destroy', function() {
                $interval.cancel(stop);
                stop = undefined;
            });
         }]);
</script>
</body>
</html>

templates/indexc.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
    <title>Atina</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/font-awesome/css/font-awesome.css' %}" rel="stylesheet">
     <link href="{% static 'css/animate.css' %}" rel="stylesheet">

    <!-- Custom Fonts -->

    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>





    <link href="{% static 'css/creative.min.css' %}" rel="stylesheet">





    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body ng-app="atina">
<nav class="nav nav-tabs" role="navigation">
            		<div class="navbar-header">
                		<button aria-controls="navbar" aria-expanded="false" data-target="#navbar" data-toggle="collapse" class="navbar-toggle collapsed" type="button">
                    		<i class="fa fa-reorder"></i>
                		</button>
                		<a href="{% url 'atinapp:home' %}" class="navbar-brand">Logo<br><br></a>
            		</div>
                    {% if user.is_authenticated %}
            		<div class="navbar-collapse collapse" id="navbar">

            			<ul class="nav navbar-top-links navbar-right">
                    		<li><a href="{% url 'atinapp:logout' %}"><i class="fa fa-sign-in"></i> Logout</a></li>
                		</ul>
                        Welcome user, you are loged in..

            		</div>
        		</nav>

<div class="jumbotron">
  <h1>Atina</h1>
  <p>Get your apps/device solution here</p>
  <p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a></p>
</div>
<div style="margin-top=50px;"class="container" ng-controller="messageController" ng-init="init()">
	<div class="row">
	  <div class="col-sm-4 col-md-4">
		<div class="thumbnail">

		  <div class="caption">
			<h3>Message Category</h3>
			<p>
			  <ul>
				<li ng-repeat="mtype in message_types" ng-click="get_messages(mtype.id)">
					<span ng-bind="mtype.name | uppercase " ></span>
				</li>
			</ul>
			   <ul>
				  <li ng-repeat=" k in users">
					  <span ng-bind ="k.title"></span>
				  </li>
				</ul>
			  </p>

		  </div>
		</div>
	  </div>


	  <div class="col-sm-4 col-md-4">
		<div class="thumbnail">

		  <div class="caption">
			<h3>Issues</h3>
			<p ng-show="mtype.id == id">
				<ul>
						<li ng-repeat="message in messages | filter:0" value="[[ message.id ]]" ng-model="messages" ng-click="get_child(message.id)">
							<span ng-bind="message.msg_content |uppercase"></span>
						</li>
						<span ng-bind="mtype.name | uppercase " ></span>
					</ul>
				</p>

		  </div>
		</div>
	  </div>


	  <div class="col-sm-4 col-md-4">
		<div class="thumbnail">

		  <div class="caption">
			<h3>Responses</h3>
				<p>
				  <ul>
				  <li ng-repeat="child in responses">
					  <span ng-bind="child.msg_content"></span>
				  </li>
				</ul>
			  </p>
			</div>
		</div>
	  </div>
	</div>
</div>
<div class="col-sm-5">
<div class="panel panel-success">
  <div class="panel-body">

    <form>
  <div class="form-group">
    <label>Select category</label>

    <select type="text" class="form-control">
        <option value="networking">Networking issues</option>
        <option value="networking">Hardware issues</option>
        <option value="networking">Software issues</option>
        <option value="networking">Other issues</option>
        </select>
  </div>
  <div class="form-group">
    <label for="exampleTextarea">Enter Message</label>
    <textarea class="form-control" id="exampleTextarea" rows="3"></textarea>
  </div>
  <button type="submit" class="btn btn-primary">Send</button>
</form>
</div>
  </div>
</div>
{% endif %}
<script type="text/javascript">
    var base_url = "{{request.build_absolute_uri}}";
    var caller = "home";
    var host = base_url.replace(caller,'');
   // alert(host + "groups/");
</script>
    <script src="{% static 'js/jquery-2.1.1.js' %}"></script>
	<script src="{% static 'js/angular.v1.5.2.js' %}"></script>
    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
<script type="text/javascript">
	 var mainApp = angular.module('atina', [], function($interpolateProvider) {
            $interpolateProvider.startSymbol('[[');
            $interpolateProvider.endSymbol(']]');
        });

         mainApp.controller('messageController',['$scope', '$interval', '$http', function($scope, $interval, $http) {
            $scope.message_types = [];
            $scope.messages = [];
            $scope.id = 0;
            $scope.message_types_selected = [];
            $scope.parentdata = [];
            $scope.childdata = [];
            $scope.users = [];

            $scope.get_messages = function(mid){
                //console.log(mid, $scope.message_types);

                for(var c in $scope.message_types){
                    if($scope.message_types[c].id == mid ){
                        $scope.messages = $scope.message_types[c].messages;
                        break;
                    }
                }
                $scope.id = mid;

            }

            $scope.get_child = function(parent_id){
            	//alert(parent_id);
            	console.log($scope.messages);
            //for (var k in $scope.messages){
			//var parent_id = $scope.messages[k].parent;
                function filter_for_parent(element){	if (element.parent ==  parent_id){ return true; } return false; }
                $scope.responses =  $scope.messages.filter(filter_for_parent);
              	//console.log($scope.responses);
			//}

            }
            $scope.init = function() {

                fetchData();

                //fetch data test: parent



            };

            var fetchData = function(){


                var mtype = {};
                $http({
                    method  : 'GET',
                    url : 'http://192.168.25.214:8000/atinapp/all_user/',
                }).success(function(users) {
                        //console.log(users);
                        for (var k in users )
                        {console.log (users[k].title);}

                $http({
                    method  : 'GET',
                    url : 'http://192.168.25.214:8000/atinapp/msg_type/',
                }).success(function(message_types) {
                        //console.log(message_types);
                        $http({
                            method  : 'GET',
                            url : 'http://192.168.25.214:8000/atinapp/all_msg/',
                        }).success(function(messages) {
                               //console.log(messages);
                                for(var c in message_types){
                                    mtype.name = message_types[c].msg_type;
                                    mtype.id = message_types[c].id;
                                    //console.log(mtype.name);
                                    mtype.messages=[];
                                    //console.log(mtype.messages);

                                    for(var s in messages){

                                        if(messages[s].msg_type == message_types[c].id ){
                                            mtype.messages.push(messages[s]);
                                        }

                                    }
                                    $scope.message_types.push(mtype);
                                    mtype = {};
                                }
                        });
                });
                });
            }

            // listen on DOM destroy (removal) event, and cancel the next UI update
            // to prevent updating time after the DOM element was removed.
             $scope.$on('$destroy', function() {
                $interval.cancel(stop);
                stop = undefined;
            });
         }]);
</script>
</body>
</html>

templates/invalid_login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>error</title>
</head>
<body>
<h1>invalid login</h1>
</body>
</html>

templates/login.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
    <title>Atina</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/font-awesome/css/font-awesome.css' %}" rel="stylesheet">
     <link href="{% static 'css/animate.css' %}" rel="stylesheet">


    <!-- Custom Fonts -->
    <link href="{% static 'vendor/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>





    <link href="{% static 'css/creative.min.css' %}" rel="stylesheet">





    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

<body ng-app="atina">
<nav class="nav nav-tabs" role="navigation">
            		<div class="navbar-header">
                		<button aria-controls="navbar" aria-expanded="false" data-target="#navbar" data-toggle="collapse" class="navbar-toggle collapsed" type="button">
                    		<i class="fa fa-reorder"></i>
                		</button>
                		<a href="{% url 'atinapp:home' %}" class="navbar-brand">Logo<br><br></a>
            		</div>
            		<div class="navbar-collapse collapse" id="navbar">


            			<ul class="nav navbar-top-links navbar-right">
                    		<li><a href="{% url 'atinapp:login' %}"><i class="fa fa-sign-in"></i> Log in</a></li>
                		</ul>

                        <ul class="nav navbar-top-links navbar-right">
                    		<li><a href="{% url 'atinapp:signup' %}"><i class="fa fa-gears"></i> Sign up </a></li>
                		</ul>

                		<ul class="nav navbar-top-links navbar-right">
                    		<li><a href="/admin/"><i class="fa fa-user"></i> Admin </a></li>
                		</ul>


            			<ul class="nav navbar-top-links navbar-right active">
                    		<li><a href="{% url 'atinapp:home' %}"><i class="fa fa-dashboard"></i> Home </a></li>
                		</ul>


            		</div>
        		</nav>
    <div style="margin-top:100px;" class="container">
        <div>
            {% if messages %}
                <ul class="messages">
                    {% for message in messages %}
                    <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                    {% endfor %}
                </ul>
            {% endif %}
        </div>
        <div class="row">
            <div class="col-lg-12">
                <div class="col-md-8 col-md-offset-2">
                    <div class="panel panel-primary">
                        <div class="panel-heading">Login Form</div>
                            <div class="panel-body">
                                <form role="form" class="form-horizontal" action="/atinapp/auth_new/" method="POST">{% csrf_token %}
                                    <div class="form-group">
                                        <label for="id_username" class="col-sm-2 control-label">Username</label>
                                        <div class="col-sm-10">
                                            <input  type="username" class="form-control" id="id_username" placeholder="Username" name="username" required />
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label for="id_password" class="col-sm-2 control-label">Password</label>
                                        <div class="col-sm-10">
                                            <input  type="password" class="form-control" id="id_password" placeholder="Password" name="password" required />
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-sm-2">
                                        </div>
                                        <div class="col-sm-10">
                                            <button type="submit" class="btn btn-primary btn-sm">Login</button>
                                            <button type="button" class="btn btn-default btn-sm" id="closeBtn">Cancel</button>
                                        </div>
                                    </div>
                                </form>
            </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<script src="{% static 'js/jquery-2.1.1.js' %}"    ></script>
<!-- Bootstrap Core JavaScript -->
<script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>


</body>
</html>

templates/message_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>all message</title>
</head>
<body>


<h1>All messages</h1>
{%for obj in message_lists %}
<a href="#">{{obj.username}}</a>&nbsp;<small>{{obj.timestamp}}</small><br/>
<p>Name : {{obj.user.first_name}} {{obj.user.last_name}}</p>
<p>Message Type: {{obj.messagetype}}</p>
<p>Message: {{obj.comment}}</p>
<p>Parent: {{obj.parent}}</p>
<p>Complain Status: {{obj.compstatus}}</p>
<p>Updated: {{obj.updated}}</p>
<p>time Stamp: {{obj.timestamp}}</p>
{% endfor %}

</body>
</html>

templates/user_detail.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
    <title>{{title}}</title>

</head>
<body>
<h1>{{ username }} &nbsp; Detail</h1>
<span>Title: {{title}}</span><br/>
<span>Firstname: {{instance.first_name}}</span><br/>
<span>Lastname: {{instance.last_name}}</span><br/>
<span>Email: {{instance.email}}</span><br/>
<span>Joined: {{timestamp }} ago</span><br/>

<span>Address: {{address}}</span><br/>
<span>Address 2: {{address_2}}</span><br/>
<span>Country: {{country}}</span><br/>
<span>State: {{state}}</span><br/>
<span>Zip Code: {{zip_code}}</span><br/>
<span>Phone: {{mobile}}</span>

<p><img src='{{ image.url }}'></p>


</body>
</html>

templates/user_list.html
<!DOCTYPE html>
<html>
<head>
    <title>Home page</title>
</head>
<body>
<h1>All users information</h1>
{%for obj in object_lists %}

<p>Name : {{obj.first_name}} {{obj.last_name}}</p>
<p>ID: {{obj.userprofile.id}}</p>
<p>Email: {{obj.email}}</p>
<p>Address: {{obj.userprofile.address}}</p>
<p>Address 2: {{obj.userprofile.address_2}}</p>
<p>Address 3: {{obj.userprofile.address_3}}</p>
<p>Mobile: {{obj.userprofile.mobile}}</p>
<p>Country: {{obj.userprofile.country}}</p>
<p>State: {{obj.userprofile.state}} </p>

{% endfor %}
</body>
</html>